title: Hewey-do-pro
email: hola@ramonh.dev
description: >- # this means to ignore newlines until "baseurl:"
  Me being a doof.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: senorHuidobro
github_username:  ramonh

# Build settings
theme: minima
plugins:
  - jekyll-feed
destination: dist
source: src
exclude: ['node_modules']
